const mysql = require('mysql2/promise');
require('dotenv').config();

async function updatePassword() {
    const connection = await mysql.createConnection({
        host: process.env.DB_HOST,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_NAME
    });

    // Valid hash for 'password123' generated by the installed bcrypt version
    // Use the one from the debug output or generate a fresh one here to be safe
    // $2b$10$4RgLxBOf9j.RLX9txhEjb.nFpKMFMSgAW9gmi2olXp1k8tqhAWX9m
    const newHash = '$2b$10$4RgLxBOf9j.RLX9txhEjb.nFpKMFMSgAW9gmi2olXp1k8tqhAWX9m';

    try {
        console.log('Connected to MySQL...');
        const [result] = await connection.execute(
            'UPDATE staff SET password = ? WHERE email = ?',
            [newHash, 'john@example.com']
        );
        console.log(`Updated ${result.affectedRows} row(s). Password reset to 'password123'.`);
    } catch (err) {
        console.error('Error updating password:', err);
    } finally {
        await connection.end();
    }
}

updatePassword();
